apiVersion: apps/v1
kind: Deployment
metadata: 
  name: go-api
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: go-api 
  template: 
    metadata: 
      labels: 
        app: go-api
    spec: 
      containers: 
      - name: go-api
        image: go-api:latest
        ports: 
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: go-api-service
spec: 
  selector: 
    app: go-api
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
